### ISSUE TITLE
Project creation raises ImportError

### ISSUE THREAD

**Issue by myersjustinc** [associatedpress/datakit-core#2]
Tried creating a project with [cookiecutter-r-project](https://github.com/associatedpress/cookiecutter-r-project), but I got this error instead:

```
$ datakit project:create --template gh:associatedpress/cookiecutter-r-project
Traceback (most recent call last):
  File "/Users/idguser/.virtualenvs/datakit/bin/datakit", line 9, in <module>
    load_entry_point('datakit-core==0.1', 'console_scripts', 'datakit')()
  File "/Users/idguser/.virtualenvs/datakit/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/idguser/.virtualenvs/datakit/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Users/idguser/.virtualenvs/datakit/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Users/idguser/.virtualenvs/datakit/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'datakit.main'
```

Environment was Python 3.5.2 (Homebrew install) on a Mac (10.10.5), in a virtualenv generated by `mkvirtualenv` (13.1.0). Installed the following before attempting to run `datakit project:create` as shown:

```
$ cat requirements.txt
-e git+https://github.com/associatedpress/datakit-core#egg=datakit-core
#-e git+ssh://git@github.com/associatedpress/datakit-core.git#egg=datakit-core
-e git+ssh://git@ctcinteract-svn01.ap.org/datakit-project.git#egg=datakit-project
```

Tried once unsuccessfully to reproduce the error, so this is all I've got for now.

**Comment by zstumgoren** [comment]
I was also never able to reproduce. Closing this for now but we can re-open or file anew if it arises again.
